### ISSUE TITLE
The Guild Contributor Docs

### ISSUE THREAD

**Issue by tvvignesh** [the-guild-org/the-guild-website#290]
Hi. As discussed with @Urigo I will be working on a PR to contributor docs for anyone who wants to contribute to the OSS projects from The Guild making them comfortable when they start (like me 😅)

While the process is same for all OSS projects, all of them follow a different set of standards, conventions, processes and also have a set criteria for people to transition from contributors to maintainers (like you guys discussed in graphqljs repo). It is better to have all of them documented in one place and we can link it in all the repos.

While the workflow remains similar for all repos, there might be some differences in the way you contribute to, for different repositories. Those instructions can be added in the repository respectively in addition to referencing the docs.

As @Urigo suggested, I have also created a google doc here: https://docs.google.com/document/d/1KwNOYcc8IdW8l-MBEHd2MPhlT8GAORkJHl7uah_x-g4/edit?usp=sharing to document my thought process as I go ahead.

**One question:**
Should I update the website to have the contributor docs and then send a PR to the relevant repos adding the link and custom instructions if any? I am going to document and try the instructions with the repos first hand and see if I can generalize them.

**PS:** Will be taking some inspirations from other OSS repos as well.

**CC:** @dotansimha @ardatan

**Comment by Urigo** [comment]
@tvvignesh the idea of generalizing structure and contributor docs is amazing!
I even think that once it's there, we could see if there are more repos that are not The Guild's that might benefit from the same structure and instructions, or even we can learn from them and adjust ours.

It's important that the doc won't only show the path and general things to do, but also technical specifics.
I also think that creating very short videos for each step would be a really amazing thing!

About where to place the initial/central doc, I'm not sure the website's repo is the best place.
Maybe we could create a new repo, but for now maybe adding a new contributors readme file on this repo would be a good start: https://github.com/the-guild-org/Stack/

I've also made some suggestions in the GDoc

**Comment by tvvignesh** [comment]
> I even think that once it's there, we could see if there are more repos that are not The Guild's that might benefit from the same structure and instructions, or even we can learn from them and adjust ours.

@Urigo I do see a lot of repos already having amazing instructions for their contributors. Some examples:

Angular - https://github.com/angular/angular/blob/master/CONTRIBUTING.md
Typescript - https://github.com/microsoft/TypeScript/blob/master/CONTRIBUTING.md
Node.js - https://github.com/nodejs/node/blob/master/CONTRIBUTING.md
OPA - https://github.com/open-policy-agent/opa/blob/master/CONTRIBUTING.md
Graphqljs - https://github.com/graphql/graphql-js/blob/master/.github/CONTRIBUTING.md

And as I go through all of them, while they have similar instructions, they also have instructions which are specific to the project. Already started writing a CONTRIBUTING file for The Guild. Will send a PR.

> I also think that creating very short videos for each step would be a really amazing thing!

Sure. Will try to do it myself and will create videos for every step as you mentioned.

> but for now maybe adding a new contributors readme file on this repo would be a good start: https://github.com/the-guild-org/Stack/

Sure. Will send a PR there.

>I've also made some suggestions in the GDoc

Updated it.

**Comment by tvvignesh** [comment]
@Urigo Sent a PR here: https://github.com/the-guild-org/Stack/pull/9
