### ISSUE TITLE
Search doesn't show nice results

### ISSUE THREAD

**Issue by maticzav** [the-guild-org/the-guild-website#422]
Results are not nice when searching on https://envelop.dev, https://swift-graphql.com, ....
![Screenshot 2021-07-26 at 18 52 57](https://user-images.githubusercontent.com/3924224/127028277-6d6a9b65-0cd8-4323-86dc-f11cb30c1cc2.png)

**Comment by dotansimha** [comment]
@tvvignesh @kamilkisiela

**Comment by kamilkisiela** [comment]
Adjust selectors

**Comment by Urigo** [comment]
@kamilkisiela is that fixed with your latest changes?

**Comment by kamilkisiela** [comment]
![Uploading Zrzut ekranu 2021-08-3 o 09.16.25.png…]()
