### ISSUE TITLE
Adjust` @theguild/components` v1.8.2 

### ISSUE THREAD

**Issue by B2o5T** [the-guild-org/the-guild-website#522]
this [PR](https://github.com/the-guild-org/the-guild-website/pull/508) fix helix logo but breaks modal

![image](https://user-images.githubusercontent.com/7361780/143777796-e8bdabe9-adbc-4bea-8732-7c7a0dc4e514.png)

**Comment by dotansimha** [comment]
@B2o5T thanks!! 
Can you please also update the link to point https://www.graphql-helix.com/ (it's live now)

**Comment by B2o5T** [comment]
done in this PR https://github.com/the-guild-org/the-guild-components/pull/270/files
and I'll fix soon modal in this repo
