### ISSUE TITLE
Blog Sync can't extract metadata

### ISSUE THREAD

**Issue by kamilkisiela** [the-guild-org/the-guild-website#547]
metadata is `{}`, that's why it fails https://github.com/the-guild-org/the-guild-website/runs/4581400459?check_suite_focus=true

**Comment by kamilkisiela** [comment]
Visitor in `extractMeta` never gets to `mdxjsEsm`, `mdxJsxFlowElement` nodes.

**Comment by dotansimha** [comment]
fixed
