### ISSUE TITLE
Blog Post: typescript union discrimination/ type guards

### ISSUE THREAD

**Issue by TuvalSimha** [the-guild-org/the-guild-website#708]
- [ ] Intro Typescript
- [ ] Project example
- [ ] Explain union discrimination/ type guards
- [ ] Explain Codegen
- [ ] Explain fragments
- [ ] Explain how union discrimination/ type guards works with Codegen
- [ ] Compare, pros and cons 
- [ ] Conclusion 
- [ ] Summary

**Comment by TuvalSimha** [comment]
Closes #715

**Comment by B2o5T** [comment]
published
