### ISSUE TITLE
Found broken `/blog/announcing-graphql-hive-public` link. Please fix!

### ISSUE THREAD

**Issue by pfeffer** [the-guild-org/the-guild-website#815]

**Comment by ardatan** [comment]
Would you contribute with a PR to fix this?

**Comment by dotansimha** [comment]
@pfeffer thanks, can you share where you found this broken link? 
The correct link seems to be https://the-guild.dev/blog/announcing-graphql-hive-release

**Comment by dotansimha** [comment]
Ok fixed by adding a redirect: https://the-guild.dev/blog/announcing-graphql-hive-public also works now
