### ISSUE TITLE
box shadow appears after click on nav bar

### ISSUE THREAD

**Issue by sagifa** [the-guild-org/the-guild-website#816]
![image](https://user-images.githubusercontent.com/95570914/188301681-5d24ae1f-61b4-47e6-a96c-d1a508ce0c25.png)
![image](https://user-images.githubusercontent.com/95570914/188301765-7fcc3b99-d4df-4cec-ac27-971ef7594495.png)

after clicking on the nav bar buttons, box-shadow appears

**Comment by B2o5T** [comment]
Thank you! finally I was fixed it, `:focus-visible` CSS pseudo-class should be used instead `:focus`
