### ISSUE TITLE
Found broken `/graphql/mesh/docs/recipes/as-gateway` link. Please fix!

### ISSUE THREAD

**Issue by javier-martinez-codurance** [the-guild-org/the-guild-website#821]
Hi everyone. 
The link is broken. Thanks

**Comment by dotansimha** [comment]
We are working on a fix, thanks @javier-martinez-codurance !

**Comment by TuvalSimha** [comment]
Hi @javier-martinez-codurance,
Thank you for the bug report, it helps us a lot!

We did some fixes and now it should work, you can find the changes we did here: https://github.com/Urigo/graphql-mesh/pull/4454
