### ISSUE TITLE
::: tip in blog posts

### ISSUE THREAD

**Issue by n1ru4l** [the-guild-org/the-guild-website#824]
![image](https://user-images.githubusercontent.com/14338007/189340262-4f8d2236-bc94-4b13-af86-3e8dd44e7c79.png)

https://the-guild.dev/blog/graphql-codegen-best-practices#name-your-operations

This is an artifact of docusaurus, we should replace it with new components.

**Comment by dotansimha** [comment]
@B2o5T i think we can close this one?

**Comment by B2o5T** [comment]
Not yet, need to replace all occurrences with Callout
