### ISSUE TITLE
blog navigation/heading is missing padding

### ISSUE THREAD

**Issue by n1ru4l** [the-guild-org/the-guild-website#825]
![image](https://user-images.githubusercontent.com/14338007/189340428-77791e73-7085-4147-ac72-d84a45b0639b.png)

see https://the-guild.dev/blog/graphql-codegen-best-practices#watch-mode

**Comment by B2o5T** [comment]
<img width="322" alt="image" src="https://user-images.githubusercontent.com/7361780/195365706-e72595d7-9a94-46db-b451-569392bf055a.png">

seems was fixed somewhere
