### ISSUE TITLE
Found broken `/graphql/codegen/docs/guides/react` link. Please fix!

### ISSUE THREAD

**Issue by MazenRefaat** [the-guild-org/the-guild-website#834]
In the [getting started](https://www.the-guild.dev/graphql/codegen/docs/getting-started/installation#global-installation) page, if you click on [React](https://www.the-guild.dev/graphql/codegen/docs/guides/react) guide link it will open a broken page `404`

**Comment by dotansimha** [comment]
Fixed, thanks @MazenRefaat
